#pragma once

/// <summary>
/// This script is autogenerated
/// Don't make any changes in the file
/// </summary>
struct SystemsState
{
      bool CameraFlySystem;
      bool CameraLookAtSystem;
      bool DirectionalShadowMapProjectionSystem;
      bool RotateSystem;
      bool TransformSystem;
      bool ViewProjectionSystem;
      SystemsState();
};

