#include "EngineCore/Pch.h"
#include "SystemsState.h"

/// <summary>
/// This script is autogenerated
/// Don't make any changes in the file
/// </summary>
SystemsState::SystemsState()
{
      CameraFlySystem = true;
      CameraLookAtSystem = true;
      DirectionalShadowMapProjectionSystem = true;
      RotateSystem = true;
      TransformSystem = true;
      ViewProjectionSystem = true;
};
