
#include "EngineCore/Pch.h"
#include "Editor/ComponentsList.h"


/// <summary>
/// This script is autogenerated
/// Don't make any changes in the file
/// </summary>

const char* allComponentsNames[componentsLength] =
{
      "CameraFreeComponent",
};


bool HasComponent(Ref<Entity> entity, const std::string& componentName)
{
      if (componentName == "CameraFreeComponent") return entity->HasComponent<CameraFreeComponent>();
      throw std::runtime_error("Not supported component type: " + componentName);
}


void AddComponent(Ref<Entity> entity, const std::string& componentName)
{
      if (HasComponent(entity, componentName)) return;

      if (componentName == "CameraFreeComponent") entity->AddComponent<CameraFreeComponent>();
}


void RemoveComponent(Ref<Entity> entity, const std::string& componentName)
{
      if (!HasComponent(entity, componentName)) return;

      if (componentName == "CameraFreeComponent") entity->RemoveComponent<CameraFreeComponent>();
}

