
#pragma once
#include <string>
#include <vector>
#include <stdexcept>

#include "EngineCore/Core/Ref.h"
#include "EngineCore/Core/Entity.h"
#include "EngineCore/Core/IComponent.h"

/// <summary>
/// This script is autogenerated
/// Don't make any changes in the file
/// </summary>

const int componentsLength = 1;
extern const char* allComponentsNames[componentsLength];


bool HasComponent(Ref<Entity> entity, const std::string& componentName);
void AddComponent(Ref<Entity> entity, const std::string& componentName);
void RemoveComponent(Ref<Entity> entity, const std::string& componentName);
