import os
import sys

def extract_component_names(folder):
    component_names = []
    for filename in os.listdir(folder):
        if filename.endswith(".h"):
            component_names.append(filename)
    return component_names

components = extract_component_names(f"{sys.argv[1]}/{sys.argv[1]}/Components")

with open(f"{sys.argv[1]}/{sys.argv[1]}/ComponentsFactory.h", 'w') as f:

#Defs
    f.write("\n")
    f.write("#pragma once\n")
    f.write("#include <string>\n")
    f.write("#include <vector>\n")
    f.write("#include <stdexcept>\n")
    
    f.write("\n")
    f.write("#include \"EngineCore/Core/Ref.h\"\n")
    f.write("#include \"EngineCore/Core/Entity.h\"\n")
    f.write("#include \"EngineCore/Core/IComponent.h\"\n")

#Notes
    f.write("\n")
    f.write("/// <summary>\n")
    f.write("/// This script is autogenerated\n")
    f.write("/// Don't make any changes in the file\n")
    f.write("/// </summary>")
    f.write("\n")

#Components array
    f.write("\n")
    f.write(f"const int componentsLength = {len(components)};\n")
    f.write("extern const char* allComponentsNames[componentsLength];\n")
    f.write("\n")

#Methods
    f.write("\n")
    f.write("bool HasComponent(Ref<Entity> entity, const std::string& componentName);\n")
    f.write("void AddComponent(Ref<Entity> entity, const std::string& componentName);\n")
    f.write("void RemoveComponent(Ref<Entity> entity, const std::string& componentName);\n")

print(f"Generated C++ for {sys.argv[1]}")