import os

systems_folder = "ExampleProject/ExampleProject/Systems"
output_file = "EngineCore/EngineCore/Core/SystemsState.cpp"

def extract_systems_names(folder):
    system_names = []
    for filename in os.listdir(folder):
        if filename.endswith(".h"):
            system_names.append(filename)
    return system_names

systems = extract_systems_names(systems_folder)

with open(output_file, 'w') as f:

#Defs
    f.write("#include \"EngineCore/Pch.h\"\n")
    f.write("#include \"SystemsState.h\"\n")

#Notes
    f.write("\n")
    f.write("/// <summary>\n")
    f.write("/// This script is autogenerated\n")
    f.write("/// Don't make any changes in the file\n")
    f.write("/// </summary>")
    f.write("\n")

    f.write("SystemsState::SystemsState()\n")
    f.write("{\n")
    for system in systems:
        f.write(f"      {system.split('.')[0].strip()} = true;\n")
    f.write("};\n")

print(f"Generated C++ for {output_file}")