
#include "EngineCore/Pch.h"
#include "Editor/ComponentsList.h"


/// <summary>
/// This script is autogenerated
/// Don't make any changes in the file
/// </summary>

const char* allComponentsNames[componentsLength] =
{
      "CameraComponent",
      "IdComponent",
      "LightComponent",
      "MaterialComponent",
      "MeshComponent",
      "NameComponent",
      "NotDestroyableEntityComponent",
      "NotSerializableEntityComponent",
      "PositionComponent",
      "RotationComponent",
      "RotationVelocityComponent",
      "ScaleComponent",
      "ShadowMapComponent",
      "UboModelComponent",
      "UboWorldComponent",
};


bool HasComponent(Ref<Entity> entity, const std::string& componentName)
{
      if (componentName == "CameraComponent") return entity->HasComponent<CameraComponent>();
      if (componentName == "IdComponent") return entity->HasComponent<IdComponent>();
      if (componentName == "LightComponent") return entity->HasComponent<LightComponent>();
      if (componentName == "MaterialComponent") return entity->HasComponent<MaterialComponent>();
      if (componentName == "MeshComponent") return entity->HasComponent<MeshComponent>();
      if (componentName == "NameComponent") return entity->HasComponent<NameComponent>();
      if (componentName == "NotDestroyableEntityComponent") return entity->HasComponent<NotDestroyableEntityComponent>();
      if (componentName == "NotSerializableEntityComponent") return entity->HasComponent<NotSerializableEntityComponent>();
      if (componentName == "PositionComponent") return entity->HasComponent<PositionComponent>();
      if (componentName == "RotationComponent") return entity->HasComponent<RotationComponent>();
      if (componentName == "RotationVelocityComponent") return entity->HasComponent<RotationVelocityComponent>();
      if (componentName == "ScaleComponent") return entity->HasComponent<ScaleComponent>();
      if (componentName == "ShadowMapComponent") return entity->HasComponent<ShadowMapComponent>();
      if (componentName == "UboModelComponent") return entity->HasComponent<UboModelComponent>();
      if (componentName == "UboWorldComponent") return entity->HasComponent<UboWorldComponent>();
      throw std::runtime_error("Not supported component type: " + componentName);
}


void AddComponent(Ref<Entity> entity, const std::string& componentName)
{
      if (HasComponent(entity, componentName)) return;

      if (componentName == "CameraComponent") entity->AddComponent<CameraComponent>();
      if (componentName == "IdComponent") entity->AddComponent<IdComponent>();
      if (componentName == "LightComponent") entity->AddComponent<LightComponent>();
      if (componentName == "MaterialComponent") entity->AddComponent<MaterialComponent>();
      if (componentName == "MeshComponent") entity->AddComponent<MeshComponent>();
      if (componentName == "NameComponent") entity->AddComponent<NameComponent>();
      if (componentName == "NotDestroyableEntityComponent") entity->AddComponent<NotDestroyableEntityComponent>();
      if (componentName == "NotSerializableEntityComponent") entity->AddComponent<NotSerializableEntityComponent>();
      if (componentName == "PositionComponent") entity->AddComponent<PositionComponent>();
      if (componentName == "RotationComponent") entity->AddComponent<RotationComponent>();
      if (componentName == "RotationVelocityComponent") entity->AddComponent<RotationVelocityComponent>();
      if (componentName == "ScaleComponent") entity->AddComponent<ScaleComponent>();
      if (componentName == "ShadowMapComponent") entity->AddComponent<ShadowMapComponent>();
      if (componentName == "UboModelComponent") entity->AddComponent<UboModelComponent>();
      if (componentName == "UboWorldComponent") entity->AddComponent<UboWorldComponent>();
}


void RemoveComponent(Ref<Entity> entity, const std::string& componentName)
{
      if (!HasComponent(entity, componentName)) return;

      if (componentName == "CameraComponent") entity->RemoveComponent<CameraComponent>();
      if (componentName == "IdComponent") entity->RemoveComponent<IdComponent>();
      if (componentName == "LightComponent") entity->RemoveComponent<LightComponent>();
      if (componentName == "MaterialComponent") entity->RemoveComponent<MaterialComponent>();
      if (componentName == "MeshComponent") entity->RemoveComponent<MeshComponent>();
      if (componentName == "NameComponent") entity->RemoveComponent<NameComponent>();
      if (componentName == "NotDestroyableEntityComponent") entity->RemoveComponent<NotDestroyableEntityComponent>();
      if (componentName == "NotSerializableEntityComponent") entity->RemoveComponent<NotSerializableEntityComponent>();
      if (componentName == "PositionComponent") entity->RemoveComponent<PositionComponent>();
      if (componentName == "RotationComponent") entity->RemoveComponent<RotationComponent>();
      if (componentName == "RotationVelocityComponent") entity->RemoveComponent<RotationVelocityComponent>();
      if (componentName == "ScaleComponent") entity->RemoveComponent<ScaleComponent>();
      if (componentName == "ShadowMapComponent") entity->RemoveComponent<ShadowMapComponent>();
      if (componentName == "UboModelComponent") entity->RemoveComponent<UboModelComponent>();
      if (componentName == "UboWorldComponent") entity->RemoveComponent<UboWorldComponent>();
}

